apiVersion: v1
kind: Secret
metadata:
  name: mysql-presence-secret
  namespace: databases
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: presence
  MYSQL_PASSWORD: presencepassword
