apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-service
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitment-service
  template:
    metadata:
      labels:
        app: recruitment-service
    spec:
      containers:
        - name: recruitment-service
          image: ihab0/recruitment-service:latest
          ports:
            - containerPort: 8095
          env:
            - name: MINIO_URL
              value: "http://minio.platform:9000"
            - name: CLAMAV_HOST
              value: "clamav.platform"
