apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: platform
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: Admin123!

  DB_USERNAME: keycloak
  DB_PASSWORD: KeycloakDb123!
