apiVersion: v1
kind: Secret
metadata:
  name: mysql-recruitment-secret
  namespace: databases
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: recruitment
  MYSQL_PASSWORD: recruitmentpassword
