apiVersion: v1
kind: Secret
metadata:
  name: mysql-employee-secret
  namespace: databases
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: employee
  MYSQL_PASSWORD: employeepassword
