apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-service
  - employee-service
  - recruitment-service
  - organisation-service
  - leave-service
  - presence-service
  - gateway-service
  - config-service
  - dicovery-service