apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: ihab0/config-service:latest
          ports:
            - containerPort: 9999
          env:
            - name: EUREKA_URL
              value: "http://discovery-service:8761/eureka"

            - name: CONFIG_REPO_URI
              value: "https://github.com/IhabChouaibi/config-pfa"

            - name: CONFIG_REPO_BRANCH
              value: "main"