apiVersion: v1
kind: Secret
metadata:
  name: mysql-leave-secret
  namespace: databases
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: leave
  MYSQL_PASSWORD: leavepassword
